spring.application.name=taskapi

spring.datasource.hikari.username=your_username
spring.datasource.password=your_password
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
